---
fixtures:
  forge_modules:
    apt:
      repo: puppetlabs/apt
      ref: 2.4.0
    concat:
      repo: puppetlabs/concat
      ref: 2.2.1
    dhcp:
      repo: theforeman/dhcp
      ref: 3.1.0
    dns:
      repo: theforeman/dns
      ref: 4.1.0
    extlib:
      repo: puppet/extlib
      ref: 1.1.0
    foreman:
      repo: theforeman/foreman
      ref: 7.2.0
    mysql:
      repo: puppetlabs/mysql
      ref: 3.11.0
    puppet:
      repo: theforeman/puppet
      ref: 7.1.1
    stdlib:
      repo: puppetlabs/stdlib
      ref: 4.20.0
    tftp:
      repo: theforeman/tftp
      ref: 2.0.0
    xinetd:
      repo: puppetlabs/xinetd
      ref: 2.0.0
  symlinks:
    foreman_proxy: "#{source_dir}"
    test: "#{source_dir}/spec/static_fixtures/test_module"
